### ISSUE TITLE
Q/A : Git & Open sourcing

### ISSUE THREAD

**Issue by adilshehzad786** [adilshehzad786/github-webinar#1]
If you have any Question please ask

**Comment by AbdullahKhanASI** [comment]
Can you please send me any link on how I can automate push commands for one of my project folder so it uploads new data automatically when I run a script?

**Comment by adilshehzad786** [comment]
Hello @abdullah-abwisk 
These are the following Steps 

- [ ]  Create a Repository on GitHub
- [ ]  After Creating, Go to Github Actions and Click on Create a  manual action

`
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: docker lint
      run: |
        npm install
        npm run build --if-present
        npm test
    - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
      name: shell linter
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

- [ ]  create Your Secret Token 
- [ ]  Insert Token to Your Repo  Secret Section

More Information: https://github.com/mikeal/publish-to-github-action/tree/master/.github/workflows

I Hope This Helps you out. Can you take a Minute and provide me your valuable [Feedback ](https://github.com/adilshehzad786/github-webinar/issues/2)
https://github.com/adilshehzad786/github-webinar/issues/2
