### ISSUE TITLE
Feedback : Git & OpenSourcing

### ISSUE THREAD

**Issue by adilshehzad786** [adilshehzad786/github-webinar#2]
Please Provide us your Valuable Feedback

**Comment by adilshehzad786** [comment]
![image](https://user-images.githubusercontent.com/53600644/102597123-ff7a1980-413b-11eb-891d-98b919d1cbd2.png)

**Comment by AbdullahKhanASI** [comment]
How to pull files from a repo?

**Comment by adilshehzad786** [comment]
@abdullah-abwisk  when you create a change on Github Repository 
You can pull from following commands

_git pull_

**Comment by ubaidrao** [comment]
Hello Dear Adil How are You ?
I was apply for GitHub Pack in 2 December 2020 but still I have not receive an email and my request has been approve but I  have not receive an email of Developer student Tool Pack please tell me what I to do now ?
![Screenshot (193)](https://user-images.githubusercontent.com/43249290/102515621-cb591700-40af-11eb-9954-3e8919da99c6.png)

**Comment by jawadaminkp** [comment]
It went quite well!

**Comment by adilshehzad786** [comment]
Hey @ubaidrao 
You Request is already approved and will expire on **DEC 2, 2021**
Check your Pack from here https://education.github.com/benefits

**Comment by adilshehzad786** [comment]
@jawadaminkp  Thanks buddy

**Comment by adilshehzad786** [comment]
@jawadaminkp Thanks

**Comment by omar-saleem** [comment]
Could you kindly guide about the process of becoming a Github Campus Expert? What are the prerequisites, what should we learn before the application in February 2021, what are the benefits?
Thank you.

**Comment by ahsanmangal** [comment]
@adilshehzad786 It was really an amazing session I learn a  lot of new things

**Comment by adilshehzad786** [comment]
Hey @omarsaleem101  
You can check all the details here http://githubcampus.expert/
According to my experience

* Github Commit & Contributions matter
*  Approved GitHub Student Developer Pack
*  Your Portfolio on GitHub pages (Optional)
Polish your GitHub Portfolio Creates chances to become a GitHub Campus Expert.

**Comment by adilshehzad786** [comment]
@ahsanmangal  Thanks

**Comment by ayeshasiddiqa161** [comment]
That was a remarkable webinar!

**Comment by adilshehzad786** [comment]
Thanks @AyeshaSiddi

**Comment by jawadaminkp** [comment]
It was indeed a very fruitful session Mr Adil. You delivered it the best way possible. It added to my enthusiasm for adopting professional practices and I am now more empowered on my way to becoming an employable graduate. Young minds like you with such technical expertise happens to be inspiration for many beginners like me. Keep Inspiring your way.
Much obliged!

**Comment by adilshehzad786** [comment]
`Thank you so much `  @jawadaminkp

**Comment by MuhammadZainTariq1999** [comment]
This session was a quite interesting as well as very interactive further through this i know about industrial standards for version control thank you adil for this tremendous webinar

**Comment by adilshehzad786** [comment]
Thanks, @MuhammadZainTariq1999
